spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useunicode=true&characterEncoding=utf8
    username: root
    password: root
    maxActive: 5
    minActive: 2