CREATE TABLE IF NOT EXISTS `users`(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id` ASC)
)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;